### ISSUE TITLE
aws-s3-virusscan not processing items from ScanQueue

### ISSUE THREAD

**Issue by echocentral** [widdix/aws-s3-virusscan#32]
After working successfully for several months, aws-s3-virusscan stopped processing items from the ScanQueue on 9/3/2018 at around 5:30 UTC.

**Comment by michaelwittig** [comment]
All logs are reported to CloudWatch Logs. Could you check them for potential errors?

**Comment by echocentral** [comment]
Thanks Michael, Andrew here:

This in var/log/cfn-init.log:
```
10:13:29
2018-03-12 10:13:29,168 [ERROR] Could not restart service clamd.scan; return code was 1
10:13:29
2018-03-12 10:13:29,168 [DEBUG] Service output: Stopping clamd.scan: [FAILED]
10:13:29
Starting clamd.scan: ERROR: LOCAL: Socket file /var/run/clamd.scan/clamd.sock could not be bound: No such file or directory
10:13:29
[FAILED]
10:13:29
2018-03-12 10:13:29,169 [ERROR] Error encountered during build of config: Could not restart clamd.scan
10:13:29
Traceback (most recent call last): File "/usr/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 542, in run_config CloudFormationCarpenter(config, self._auth_config).build(worklog) File "/usr/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 270, in build CloudFormationCarpenter._serviceTools[manager]().apply(services, changes) File "/usr/lib/python2.7/dis
10:13:29
ToolError: Could not restart clamd.scan
10:13:29
2018-03-12 10:13:29,169 [ERROR] -----------------------BUILD FAILED!------------------------
10:13:29
2018-03-12 10:13:29,171 [ERROR] Unhandled exception during build: Could not restart clamd.scan
10:13:29
Traceback (most recent call last): File "/opt/aws/bin/cfn-init", line 171, in <module> worklog.build(metadata, configSets) File "/usr/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 129, in build Contractor(metadata).build(configSets, self) File "/usr/lib/python2.7/dist-packages/cfnbootstrap/construction.py", line 530, in build self.run_config(config, worklog) F
10:13:29
ToolError: Could not restart clamd.scan
10:13:29
2018-03-12 10:13:29,454 [DEBUG] CloudFormation client initialized with endpoint https://cloudformation.eu-west-1.amazonaws.com
10:13:29
2018-03-12 10:13:29,455 [DEBUG] Signaling resource ScanAutoScalingGroup in stack aws-s3-virusscan with unique ID i-09c3869dfff037de5 and status FAILURE
```

This is from var/log/cloud-init-output.log
```
10:13:30
Error occurred during build: Could not restart clamd.scan
10:13:30
+ /opt/aws/bin/cfn-signal -e 1 --stack aws-s3-virusscan --resource ScanAutoScalingGroup --region eu-west-1
10:13:30
ValidationError: Stack arn:aws:cloudformation:eu-west-1:495718086527:stack/aws-s3-virusscan/f9998090-a856-11e7-aef9-50a6863404d2 is in CREATE_COMPLETE state and cannot be signaled
10:13:30
Mar 12 10:13:29 cloud-init[2698]: util.py[WARNING]: Failed running /var/lib/cloud/instance/scripts/part-001 [1]
10:13:30
Mar 12 10:13:29 cloud-init[2698]: cc_scripts_user.py[WARNING]: Failed to run module scripts-user (scripts in /var/lib/cloud/instance/scripts)
10:13:30
Mar 12 10:13:29 cloud-init[2698]: util.py[WARNING]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python2.7/dist-packages/cloudinit/config/cc_scripts_user.pyc'>) failed
10:13:30
ci-info: no authorized ssh keys fingerprints found for user ec2-user.
10:13:30
Cloud-init v. 0.7.6 finished at Mon, 12 Mar 2018 10:13:29 +0000. Datasource DataSourceEc2. Up 119.11 seconds
```

This from var/log/secure:
```
10:07:58
Mar 13 10:07:58 ip-10-0-8-122 sshd[20922]: Received disconnect from 42.7.26.15: 11: [preauth]
10:11:04
Mar 13 10:11:04 ip-10-0-8-122 sshd[21000]: Disconnecting: Too many authentication failures for root [preauth]
```

**Comment by michaelwittig** [comment]
can you check `/var/log/messages` as well? Question is why `Could not restart clamd.scan` happens...

**Comment by echocentral** [comment]
From `/var/log/messages`:

```
10:43:21
Mar 13 10:43:21 ip-10-0-8-122 freshclam[21649]: ClamAV update process started at Tue Mar 13 10:43:21 2018
10:43:21
Mar 13 10:43:21 ip-10-0-8-122 freshclam[21649]: Your ClamAV installation is OUTDATED!
10:43:21
Mar 13 10:43:21 ip-10-0-8-122 freshclam[21649]: Local version: 0.99.3 Recommended version: 0.99.4
10:43:21
Mar 13 10:43:21 ip-10-0-8-122 freshclam[21649]: DON'T PANIC! Read http://www.clamav.net/documents/upgrading-clamav
10:43:21
Mar 13 10:43:21 ip-10-0-8-122 freshclam[21649]: main.cvd is up to date (version: 58, sigs: 4566249, f-level: 60, builder: sigmgr)
10:43:22
Mar 13 10:43:22 ip-10-0-8-122 freshclam[21649]: getfile: daily-24389.cdiff not found on database.clamav.net (IP: 193.1.193.64)
10:43:22
Mar 13 10:43:22 ip-10-0-8-122 freshclam[21649]: getpatch: Can't download daily-24389.cdiff from database.clamav.net
10:43:22
Mar 13 10:43:22 ip-10-0-8-122 freshclam[21649]: getfile: daily-24389.cdiff not found on database.clamav.net (IP: 78.158.65.73)
10:43:22
Mar 13 10:43:22 ip-10-0-8-122 freshclam[21649]: getpatch: Can't download daily-24389.cdiff from database.clamav.net
10:43:22
Mar 13 10:43:22 ip-10-0-8-122 freshclam[21649]: Trying host database.clamav.net (129.67.1.218)...
10:43:22
Mar 13 10:43:22 ip-10-0-8-122 freshclam[21649]: Downloading daily-24389.cdiff [100%]
10:43:27
Mar 13 10:43:27 ip-10-0-8-122 freshclam[21649]: daily.cld updated (version: 24389, sigs: 1875879, f-level: 63, builder: neo)
10:43:27
Mar 13 10:43:27 ip-10-0-8-122 freshclam[21649]: bytecode.cvd is up to date (version: 319, sigs: 75, f-level: 63, builder: neo)
10:43:34
Mar 13 10:43:34 ip-10-0-8-122 freshclam[21649]: Database updated (6442203 signatures) from database.clamav.net (IP: 129.67.1.218)
10:43:56
Mar 13 10:43:56 ip-10-0-8-122 dhclient[2179]: XMT: Solicit on eth0, interval 113100ms.
10:45:49
Mar 13 10:45:49 ip-10-0-8-122 dhclient[2179]: XMT: Solicit on eth0, interval 117800ms.
10:47:47
Mar 13 10:47:47 ip-10-0-8-122 dhclient[2179]: XMT: Solicit on eth0, interval 123260ms.
10:48:22
Mar 13 10:48:22 ip-10-0-8-122 dhclient[2081]: DHCPREQUEST on eth0 to 10.0.0.1 port 67 (xid=0x472c17eb)
10:48:22
Mar 13 10:48:22 ip-10-0-8-122 dhclient[2081]: DHCPACK from 10.0.0.1 (xid=0x472c17eb)
10:48:23
Mar 13 10:48:23 ip-10-0-8-122 dhclient[2081]: bound to 10.0.8.122 -- renewal in 1385 seconds.
10:48:23
Mar 13 10:48:23 ip-10-0-8-122 ec2net: [get_meta] Trying to get http://169.254.169.254/latest/meta-data/network/interfaces/macs/06:45:e9:b2:08:0c/local-ipv4s
10:48:23
Mar 13 10:48:23 ip-10-0-8-122 ec2net: [rewrite_aliases] Rewriting aliases of eth0
10:49:50
Mar 13 10:49:50 ip-10-0-8-122 dhclient[2179]: XMT: Solicit on eth0, interval 113390ms.
10:51:44
Mar 13 10:51:44 ip-10-0-8-122 dhclient[2179]: XMT: Solicit on eth0, interval 126560ms.
```

**Comment by michaelwittig** [comment]
Hi @echocentral the entry from `/var/log/cloud-init-output.log` indicates that the start failed at around 
10:13:30

Your `/var/log/messages` start at 10.43. Can you provide the `/var/log/messages` from around 10:13:30 ?

**Comment by echocentral** [comment]
Hi Michael. Here you go. To my eye, not a lot there ...

```
09:51:13
Mar 13 09:51:13 ip-10-0-8-122 ec2net: [get_meta] Trying to get http://169.254.169.254/latest/meta-data/network/interfaces/macs/06:45:e9:b2:08:0c/local-ipv4s
09:51:13
Mar 13 09:51:13 ip-10-0-8-122 ec2net: [rewrite_aliases] Rewriting aliases of eth0
09:52:08
Mar 13 09:52:08 ip-10-0-8-122 dhclient[2179]: XMT: Solicit on eth0, interval 129920ms.
09:54:18
Mar 13 09:54:18 ip-10-0-8-122 dhclient[2179]: XMT: Solicit on eth0, interval 113160ms.
09:56:12
Mar 13 09:56:12 ip-10-0-8-122 dhclient[2179]: XMT: Solicit on eth0, interval 109870ms.
09:58:02
Mar 13 09:58:02 ip-10-0-8-122 dhclient[2179]: XMT: Solicit on eth0, interval 116560ms.
09:59:58
Mar 13 09:59:58 ip-10-0-8-122 dhclient[2179]: XMT: Solicit on eth0, interval 110040ms.
10:01:48
Mar 13 10:01:48 ip-10-0-8-122 dhclient[2179]: XMT: Solicit on eth0, interval 112900ms.
10:03:41
Mar 13 10:03:41 ip-10-0-8-122 dhclient[2179]: XMT: Solicit on eth0, interval 116430ms.
10:05:38
Mar 13 10:05:38 ip-10-0-8-122 dhclient[2179]: XMT: Solicit on eth0, interval 108580ms.
10:07:27
Mar 13 10:07:27 ip-10-0-8-122 dhclient[2179]: XMT: Solicit on eth0, interval 128530ms.
10:09:35
Mar 13 10:09:35 ip-10-0-8-122 dhclient[2179]: XMT: Solicit on eth0, interval 128550ms.
10:11:44
Mar 13 10:11:44 ip-10-0-8-122 dhclient[2179]: XMT: Solicit on eth0, interval 111730ms.
10:13:36
Mar 13 10:13:36 ip-10-0-8-122 dhclient[2179]: XMT: Solicit on eth0, interval 118100ms.
10:15:34
Mar 13 10:15:34 ip-10-0-8-122 dhclient[2179]: XMT: Solicit on eth0, interval 128210ms.
10:17:42
Mar 13 10:17:42 ip-10-0-8-122 dhclient[2179]: XMT: Solicit on eth0, interval 126070ms.
10:19:15
Mar 13 10:19:15 ip-10-0-8-122 dhclient[2081]: DHCPREQUEST on eth0 to 10.0.0.1 port 67 (xid=0x472c17eb)
10:19:15
Mar 13 10:19:15 ip-10-0-8-122 dhclient[2081]: DHCPACK from 10.0.0.1 (xid=0x472c17eb)
10:19:15
Mar 13 10:19:15 ip-10-0-8-122 dhclient[2081]: bound to 10.0.8.122 -- renewal in 1747 seconds.
10:19:15
Mar 13 10:19:15 ip-10-0-8-122 ec2net: [get_meta] Trying to get http://169.254.169.254/latest/meta-data/network/interfaces/macs/06:45:e9:b2:08:0c/local-ipv4s
10:19:15
Mar 13 10:19:15 ip-10-0-8-122 ec2net: [rewrite_aliases] Rewriting aliases of eth0
10:19:48
Mar 13 10:19:48 ip-10-0-8-122 dhclient[2179]: XMT: Solicit on eth0, interval 124100ms.
10:21:53
Mar 13 10:21:53 ip-10-0-8-122 dhclient[2179]: XMT: Solicit on eth0, interval 120080ms.
10:23:53
Mar 13 10:23:53 ip-10-0-8-122 dhclient[2179]: XMT: Solicit on eth0, interval 114430ms.
```

**Comment by echocentral** [comment]
oops I see that was the wrong day. new logs incoming.

**Comment by echocentral** [comment]
There: those are from 12th March `/var/log/messages`

```
10:11:43
Mar 12 10:11:43 ip-10-0-8-122 dhclient[2179]: XMT: Solicit on eth0, interval 8400ms.
10:11:48
Mar 12 10:11:48 ip-10-0-8-122 yum[2485]: Updated: nss-util-3.28.4-3.53.amzn1.x86_64
10:11:48
Mar 12 10:11:48 ip-10-0-8-122 yum[2485]: Updated: 32:bind-libs-9.8.2-0.62.rc1.57.amzn1.x86_64
10:11:48
Mar 12 10:11:48 ip-10-0-8-122 yum[2485]: Updated: nss-softokn-freebl-3.28.3-8.41.amzn1.x86_64
10:11:48
Mar 12 10:11:48 ip-10-0-8-122 yum[2485]: Updated: nss-softokn-3.28.3-8.41.amzn1.x86_64
10:11:48
Mar 12 10:11:48 ip-10-0-8-122 yum[2485]: Updated: nss-sysinit-3.28.4-12.80.amzn1.x86_64
10:11:48
Mar 12 10:11:48 ip-10-0-8-122 yum[2485]: Installed: nss-pem-1.0.3-4.3.amzn1.x86_64
10:11:48
Mar 12 10:11:48 ip-10-0-8-122 yum[2485]: Updated: nss-3.28.4-12.80.amzn1.x86_64
10:11:48
Mar 12 10:11:48 ip-10-0-8-122 yum[2485]: Updated: file-libs-5.30-11.34.amzn1.x86_64
10:11:48
Mar 12 10:11:48 ip-10-0-8-122 yum[2485]: Updated: file-5.30-11.34.amzn1.x86_64
10:11:48
Mar 12 10:11:48 ip-10-0-8-122 yum[2485]: Updated: nss-tools-3.28.4-12.80.amzn1.x86_64
10:11:51
Mar 12 10:11:51 ip-10-0-8-122 yum[2485]: Updated: 1:java-1.7.0-openjdk-1.7.0.161-2.6.12.0.75.amzn1.x86_64
10:11:51
Mar 12 10:11:51 ip-10-0-8-122 yum[2485]: Updated: 32:bind-utils-9.8.2-0.62.rc1.57.amzn1.x86_64
10:11:51
Mar 12 10:11:51 ip-10-0-8-122 yum[2485]: Updated: kernel-tools-4.9.85-37.55.amzn1.x86_64
10:11:51
Mar 12 10:11:51 ip-10-0-8-122 yum[2485]: Updated: wget-1.18-3.28.amzn1.x86_64
10:11:51
Mar 12 10:11:51 ip-10-0-8-122 dhclient[2179]: XMT: Solicit on eth0, interval 16810ms.
10:11:51
Mar 12 10:11:51 ip-10-0-8-122 yum[2485]: Updated: aws-cfn-bootstrap-1.4-29.20.amzn1.noarch
10:11:52
Mar 12 10:11:52 ip-10-0-8-122 ntpd[2637]: ntpd 4.2.6p5@1.2349-o Wed Apr 19 22:27:48 UTC 2017 (1)
10:11:52
Mar 12 10:11:52 ip-10-0-8-122 ntpd[2638]: proto: precision = 0.101 usec
10:11:52
Mar 12 10:11:52 ip-10-0-8-122 ntpd[2638]: 0.0.0.0 c01d 0d kern kernel time sync enabled
10:11:52
Mar 12 10:11:52 ip-10-0-8-122 ntpd[2638]: Listen and drop on 0 v4wildcard 0.0.0.0 UDP 123
10:11:52
Mar 12 10:11:52 ip-10-0-8-122 ntpd[2638]: Listen normally on 1 lo 127.0.0.1 UDP 123
10:11:52
Mar 12 10:11:52 ip-10-0-8-122 ntpd[2638]: Listen normally on 2 eth0 10.0.8.122 UDP 123
10:11:52
Mar 12 10:11:52 ip-10-0-8-122 ntpd[2638]: Listening on routing socket on fd #19 for interface updates
10:12:01
Mar 12 10:12:01 ip-10-0-8-122 yum[2722]: Installed: aws-cli-plugin-cloudwatch-logs-1.4.4-1.16.amzn1.noarch
10:12:03
Mar 12 10:12:03 ip-10-0-8-122 yum[2722]: Installed: awslogs-1.1.4-1.12.amzn1.noarch
10:12:08
Mar 12 10:12:08 ip-10-0-8-122 dhclient[2179]: XMT: Solicit on eth0, interval 34920ms.
10:12:16
Mar 12 10:12:16 ip-10-0-8-122 yum[2809]: Installed: clamav-filesystem-0.99.3-1.28.amzn1.noarch
10:12:22
Mar 12 10:12:22 ip-10-0-8-122 yum[2809]: Installed: clamav-data-0.99.3-1.28.amzn1.noarch
10:12:23
Mar 12 10:12:23 ip-10-0-8-122 yum[2809]: Installed: libtool-ltdl-2.4.2-20.4.8.5.32.amzn1.x86_64
10:12:23
Mar 12 10:12:23 ip-10-0-8-122 yum[2809]: Installed: clamav-lib-0.99.3-1.28.amzn1.x86_64
10:12:23
Mar 12 10:12:23 ip-10-0-8-122 yum[2809]: Installed: clamav-server-0.99.3-1.28.amzn1.x86_64
10:12:23
Mar 12 10:12:23 ip-10-0-8-122 yum[2809]: Installed: clamav-server-sysvinit-0.99.3-1.28.amzn1.noarch
10:12:23
Mar 12 10:12:23 ip-10-0-8-122 yum[2809]: Installed: clamav-scanner-0.99.3-1.28.amzn1.noarch
10:12:23
Mar 12 10:12:23 ip-10-0-8-122 yum[2809]: Installed: clamav-scanner-sysvinit-0.99.3-1.28.amzn1.noarch
10:12:23
Mar 12 10:12:23 ip-10-0-8-122 yum[2809]: Installed: clamav-0.99.3-1.28.amzn1.x86_64
10:12:23
Mar 12 10:12:23 ip-10-0-8-122 yum[2809]: Installed: clamd-0.99.3-1.28.amzn1.x86_64
10:12:23
Mar 12 10:12:23 ip-10-0-8-122 yum[2809]: Installed: clamav-update-0.99.3-1.28.amzn1.x86_64
10:12:41
Mar 12 10:12:41 ip-10-0-8-122 freshclam[2897]: ClamAV update process started at Mon Mar 12 10:12:41 2018
10:12:41
Mar 12 10:12:41 ip-10-0-8-122 freshclam[2897]: Your ClamAV installation is OUTDATED!
10:12:41
Mar 12 10:12:41 ip-10-0-8-122 freshclam[2897]: Local version: 0.99.3 Recommended version: 0.99.4
10:12:41
Mar 12 10:12:41 ip-10-0-8-122 freshclam[2897]: DON'T PANIC! Read http://www.clamav.net/documents/upgrading-clamav
10:12:41
Mar 12 10:12:41 ip-10-0-8-122 freshclam[2897]: main.cvd is up to date (version: 58, sigs: 4566249, f-level: 60, builder: sigmgr)
10:12:43
Mar 12 10:12:43 ip-10-0-8-122 freshclam[2897]: getfile: daily-24254.cdiff not found on database.clamav.net (IP: 78.158.65.73)
10:12:43
Mar 12 10:12:43 ip-10-0-8-122 freshclam[2897]: getpatch: Can't download daily-24254.cdiff from database.clamav.net
10:12:43
Mar 12 10:12:43 ip-10-0-8-122 freshclam[2897]: getfile: daily-24254.cdiff not found on database.clamav.net (IP: 193.1.193.64)
10:12:43
Mar 12 10:12:43 ip-10-0-8-122 freshclam[2897]: getpatch: Can't download daily-24254.cdiff from database.clamav.net
10:12:43
Mar 12 10:12:43 ip-10-0-8-122 freshclam[2897]: Trying host database.clamav.net (178.79.177.182)...
10:12:43
Mar 12 10:12:43 ip-10-0-8-122 freshclam[2897]: getfile: daily-24254.cdiff not found on database.clamav.net (IP: 178.79.177.182)
10:12:43
Mar 12 10:12:43 ip-10-0-8-122 freshclam[2897]: getpatch: Can't download daily-24254.cdiff from database.clamav.net
10:12:43
Mar 12 10:12:43 ip-10-0-8-122 freshclam[2897]: Incremental update failed, trying to download daily.cvd
10:12:43
Mar 12 10:12:43 ip-10-0-8-122 dhclient[2179]: XMT: Solicit on eth0, interval 71630ms.
10:12:44
Mar 12 10:12:44 ip-10-0-8-122 freshclam[2897]: Downloading daily.cvd [100%]
10:12:54
Mar 12 10:12:54 ip-10-0-8-122 freshclam[2897]: daily.cvd updated (version: 24386, sigs: 1874812, f-level: 63, builder: neo)
10:12:54
Mar 12 10:12:54 ip-10-0-8-122 freshclam[2897]: bytecode.cvd is up to date (version: 319, sigs: 75, f-level: 63, builder: neo)
10:13:03
Mar 12 10:13:03 ip-10-0-8-122 freshclam[2897]: Database updated (6441136 signatures) from database.clamav.net (IP: 129.67.1.218)
10:13:03
Mar 12 10:13:03 ip-10-0-8-122 clamd[2935]: Received 0 file descriptor(s) from systemd.
10:13:03
Mar 12 10:13:03 ip-10-0-8-122 clamd[2935]: clamd daemon 0.99.3 (OS: linux-gnu, ARCH: x86_64, CPU: x86_64)
10:13:03
Mar 12 10:13:03 ip-10-0-8-122 clamd[2935]: Running as user clamscan (UID 497, GID 495)
10:13:03
Mar 12 10:13:03 ip-10-0-8-122 clamd[2935]: Log file size limited to 1048576 bytes.
10:13:03
Mar 12 10:13:03 ip-10-0-8-122 clamd[2935]: Reading databases from /var/lib/clamav
10:13:03
Mar 12 10:13:03 ip-10-0-8-122 clamd[2935]: Not loading PUA signatures.
10:13:03
Mar 12 10:13:03 ip-10-0-8-122 clamd[2935]: Bytecode: Security mode set to "TrustSigned".
10:13:25
Mar 12 10:13:25 ip-10-0-8-122 clamd[2935]: Loaded 6435037 signatures.
10:13:29
Mar 12 10:13:29 ip-10-0-8-122 clamd[2935]: LOCAL: Socket file /var/run/clamd.scan/clamd.sock could not be bound: No such file or directory
10:13:29
Mar 12 10:13:29 ip-10-0-8-122 ec2:
10:13:29
Mar 12 10:13:29 ip-10-0-8-122 ec2: #############################################################
10:13:29
Mar 12 10:13:29 ip-10-0-8-122 ec2: -----BEGIN SSH HOST KEY FINGERPRINTS-----
10:13:29
Mar 12 10:13:29 ip-10-0-8-122 ec2: 1024 72:9c:25:8b:e2:59:bb:70:45:c7:40:1e:a2:f8:c2:ec root@ip-10-0-8-122 (DSA)
10:13:29
Mar 12 10:13:29 ip-10-0-8-122 ec2: 256 e9:f0:46:81:a7:a6:ad:e0:f4:57:57:74:a0:7d:76:a2 root@ip-10-0-8-122 (ECDSA)
10:13:29
Mar 12 10:13:29 ip-10-0-8-122 ec2: 256 47:2f:3d:bd:9e:de:34:88:fa:a4:bd:55:dc:5a:dd:e0 (ED25519)
10:13:29
Mar 12 10:13:29 ip-10-0-8-122 ec2: 2048 c2:f1:36:8d:ce:ac:e0:22:37:14:b6:5f:c5:59:5f:78 root@ip-10-0-8-122 (RSA)
10:13:29
Mar 12 10:13:29 ip-10-0-8-122 ec2: -----END SSH HOST KEY FINGERPRINTS-----
10:13:29
Mar 12 10:13:29 ip-10-0-8-122 ec2: #############################################################
10:13:55
Mar 12 10:13:55 ip-10-0-8-122 dhclient[2179]: XMT: Solicit on eth0, interval 131110ms.
10:16:06
Mar 12 10:16:06 ip-10-0-8-122 dhclient[2179]: XMT: Solicit on eth0, interval 123060ms.
10:18:09
Mar 12 10:18:09 ip-10-0-8-122 dhclient[2179]: XMT: Solicit on eth0, interval 125590ms.
```

**Comment by michaelwittig** [comment]
"Socket file /var/run/clamd.scan/clamd.sock could not be bound: No such file or directory"  was helpful. Expect a fix shortly..

**Comment by echocentral** [comment]
Thank you Michael! Getting the queue processed now.
