### ISSUE TITLE
[ERROR] Gem failed. Output: ERROR:  Error installing aws-sdk-s3

### ISSUE THREAD

**Issue by if22** [widdix/aws-s3-virusscan#50]
Hello ,
I've found this error in _/var/log/cfn-init.log_ log file.
```
2019-03-15 05:54:21,606 [DEBUG] Checking to see if aws-sdk-s3-1.30.1 is already installed
2019-03-15 05:54:21,748 [INFO] Installing aws-sdk-s3 version 1.30.1 via gem
2019-03-15 05:54:28,616 [ERROR] Gem failed. Output: ERROR:  Error installing aws-sdk-s3:
        http-2 requires Ruby version >= 2.1.0.
Successfully installed jmespath-1.4.0
Successfully installed aws-partitions-1.144.0
Successfully installed aws-eventstream-1.0.2
Successfully installed aws-sigv4-1.1.0

2019-03-15 05:54:28,616 [ERROR] Error encountered during build of config: Failed to install gem: aws-sdk-s3-1.30.1 (return code 1)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/construction.py", line 542, in run_config
    CloudFormationCarpenter(config, self._auth_config).build(worklog)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/construction.py", line 229, in build
    changes['packages'][manager] = CloudFormationCarpenter._packageTools[manager]().apply(packages, self._auth_config)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/lang_package_tools.py", line 111, in apply
    if self._install_gem(pkg, ver):
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/lang_package_tools.py", line 155, in _install_gem
    raise ToolError("Failed to install gem: %s-%s" % (pkg, ver), result.returncode)
ToolError: Failed to install gem: aws-sdk-s3-1.30.1 (return code 1)
2019-03-15 05:54:28,617 [ERROR] -----------------------BUILD FAILED!------------------------
2019-03-15 05:54:28,618 [ERROR] Unhandled exception during build: Failed to install gem: aws-sdk-s3-1.30.1 (return code 1)
Traceback (most recent call last):
  File "/opt/aws/bin/cfn-init", line 171, in <module>
    worklog.build(metadata, configSets)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/construction.py", line 129, in build
    Contractor(metadata).build(configSets, self)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/construction.py", line 530, in build
    self.run_config(config, worklog)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/construction.py", line 542, in run_config
    CloudFormationCarpenter(config, self._auth_config).build(worklog)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/construction.py", line 229, in build
    changes['packages'][manager] = CloudFormationCarpenter._packageTools[manager]().apply(packages, self._auth_config)
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/lang_package_tools.py", line 111, in apply
    if self._install_gem(pkg, ver):
  File "/usr/lib/python2.7/site-packages/cfnbootstrap/lang_package_tools.py", line 155, in _install_gem
    raise ToolError("Failed to install gem: %s-%s" % (pkg, ver), result.returncode)
ToolError: Failed to install gem: aws-sdk-s3-1.30.1 (return code 1)
```

Could you please help me with that?

**Comment by michaelwittig** [comment]
This issue was caused by AWS breaking the ruby SDK. They fixed the issue already. Nothing to do on your side. Details: https://github.com/aws/aws-sdk-ruby/issues/1994
