### ISSUE TITLE
CloudFormaton template fails behind proxy

### ISSUE THREAD

**Issue by rmarre** [widdix/aws-s3-virusscan#69]
AWS Marketplace customers have access to support via email: hello@widdix.net

Hello,
We try to implement this CloudFormation template in our private VPC and private subnet, failing to create it, would you please advise any specific changes needed. 

Error logs are as follows:

[root@/var/log]# grep error *.log
cfn-hup.log:ConnectionError: HTTPConnectionPool(host='.....', port=8080): Max retries exceeded with url: http://169.254.169.254/latest/api/token (Caused by ProxyError('Cannot connect to proxy.', error(104, 'Connection reset by peer')))
cfn-hup.log:ConnectionError: HTTPConnectionPool(host='.....', port=8080): Max retries exceeded with url: http://169.254.169.254/latest/api/token (Caused by ProxyError('Cannot connect to proxy.', error(104, 'Connection reset by peer')))
cfn-hup.log:ConnectionError: HTTPConnectionPool(host='.....', port=8080): Max retries exceeded with url: http://169.254.169.254/latest/api/token (Caused by ProxyError('Cannot connect to proxy.', error(104, 'Connection reset by peer')))
cfn-init-cmd.log:2020-10-22 17:54:34,986 P3505 [INFO]   https://mirror.atl.genesisadaptive.com/epel/7/x86_64/repodata/repomd.xml: [Errno 14] curl#22 - "The requested URL returned error: 407"
cfn-init-cmd.log:2020-10-22 17:54:34,987 P3505 [INFO]   https://epel.mirror.constant.com/7/x86_64/repodata/7c541c1a27282c7f6dfe8a30f176650d03d56eb9a014cf00b2b9775c958aa6e3-updateinfo.xml.bz2: [Errno 14] curl#22 - "The requested URL returned error: 407"
cfn-init-cmd.log:2020-10-22 17:54:34,987 P3505 [INFO]   https://ewr.edge.kernel.org/fedora-buffet/epel/7/x86_64/repodata/256fe13c9b4274f5ab2b2c61d51d961ff7d1bb89cd8d57b6dffe1c9e78570aae-primary.sqlite.bz2: [Errno 14] curl#22 - "The requested URL returned error: 407"
cfn-init-cmd.log:2020-10-22 17:54:34,987 P3505 [INFO]   https://mirror.arizona.edu/fedora-epel/7/x86_64/repodata/256fe13c9b4274f5ab2b2c61d51d961ff7d1bb89cd8d57b6dffe1c9e78570aae-primary.sqlite.bz2: [Errno 14] curl#22 - "The requested URL returned error: 407"
cfn-init-cmd.log:2020-10-22 17:54:56,241 P3505 [ERROR] Exited with error code 1
cfn-init.log:https://mirror.atl.genesisadaptive.com/epel/7/x86_64/repodata/repomd.xml: [Errno 14] curl#22 - "The requested URL returned error: 407"
cfn-init.log:https://epel.mirror.constant.com/7/x86_64/repodata/7c541c1a27282c7f6dfe8a30f176650d03d56eb9a014cf00b2b9775c958aa6e3-updateinfo.xml.bz2: [Errno 14] curl#22 - "The requested URL returned error: 407"
cfn-init.log:https://ewr.edge.kernel.org/fedora-buffet/epel/7/x86_64/repodata/256fe13c9b4274f5ab2b2c61d51d961ff7d1bb89cd8d57b6dffe1c9e78570aae-primary.sqlite.bz2: [Errno 14] curl#22 - "The requested URL returned error: 407"
cfn-init.log:https://mirror.arizona.edu/fedora-epel/7/x86_64/repodata/256fe13c9b4274f5ab2b2c61d51d961ff7d1bb89cd8d57b6dffe1c9e78570aae-primary.sqlite.bz2: [Errno 14] curl#22 - "The requested URL returned error: 407"
cloud-init.log:ProcessExecutionError: Unexpected error while running command.
[root@/var/log]#

Thanks

**Comment by andreaswittig** [comment]
As the logs indicate, all HTTP calls fail with error code 407, which is `Proxy Authentication Required`. I assume your network routes all HTTP requests through a proxy, which requires authentication.

**Comment by rmarre** [comment]
I am using proxy authentication, getting installed require software, however some are failing; please see below logs:

========================= cfn-init-cmd.log =========================

2020-10-22 19:31:27,123 P3549 [INFO]    Transaction test succeeded
2020-10-22 19:31:27,123 P3549 [INFO]    Running transaction
2020-10-22 19:31:27,123 P3549 [INFO]      Installing : epel-release-7-11.noarch                                     1/1
2020-10-22 19:31:27,123 P3549 [INFO]      Verifying  : epel-release-7-11.noarch                                     1/1
2020-10-22 19:31:27,124 P3549 [INFO]
2020-10-22 19:31:27,124 P3549 [INFO]    Installed:
2020-10-22 19:31:27,124 P3549 [INFO]      epel-release.noarch 0:7-11
2020-10-22 19:31:27,124 P3549 [INFO]
2020-10-22 19:31:27,124 P3549 [INFO]    Complete!
2020-10-22 19:31:27,124 P3549 [INFO] ------------------------------------------------------------
2020-10-22 19:31:27,124 P3549 [INFO] Completed successfully.
2020-10-22 19:31:27,125 P3549 [INFO] ============================================================
2020-10-22 19:31:27,125 P3549 [INFO] Command a_installs
2020-10-22 19:32:51,909 P3549 [INFO] -----------------------Command Output-----------------------
2020-10-22 19:32:51,910 P3549 [INFO]    Loaded plugins: extras_suggestions, langpacks, priorities, update-motd
2020-10-22 19:32:51,910 P3549 [INFO]    https://ewr.edge.kernel.org/fedora-buffet/epel/7/x86_64/repodata/256fe13c9b4274f5ab2b2c61d51d961ff7d1bb89cd8d57b6dffe1c9e78570aae-primary.sqlite.bz2: [Errno 14] curl#22 - "The requested URL returned error: 407"
2020-10-22 19:32:51,910 P3549 [INFO]    Trying other mirror.
2020-10-22 19:32:51,910 P3549 [INFO]    https://mirror.atl.genesisadaptive.com/epel/7/x86_64/repodata/7c541c1a27282c7f6dfe8a30f176650d03d56eb9a014cf00b2b9775c958aa6e3-updateinfo.xml.bz2: [Errno 14] curl#22 - "The requested URL returned error: 407"
2020-10-22 19:32:51,910 P3549 [INFO]    Trying other mirror.
2020-10-22 19:32:51,910 P3549 [INFO]    http://mirror.twinlakes.net/epel/7/x86_64/repodata/7c541c1a27282c7f6dfe8a30f176650d03d56eb9a014cf00b2b9775c958aa6e3-updateinfo.xml.bz2: [Errno 14] HTTP Error 407 - Proxy Authentication Required
2020-10-22 19:32:51,910 P3549 [INFO]    Trying other mirror.
2020-10-22 19:32:51,910 P3549 [INFO]    https://mirror.arizona.edu/fedora-epel/7/x86_64/repodata/256fe13c9b4274f5ab2b2c61d51d961ff7d1bb89cd8d57b6dffe1c9e78570aae-primary.sqlite.bz2: [Errno 14] curl#22 - "The requested URL returned error: 407"
2020-10-22 19:32:51,910 P3549 [INFO]    Trying other mirror.
2020-10-22 19:32:51,910 P3549 [INFO]    https://epel.mirror.constant.com/7/x86_64/repodata/256fe13c9b4274f5ab2b2c61d51d961ff7d1bb89cd8d57b6dffe1c9e78570aae-primary.sqlite.bz2: [Errno 14] curl#22 - "The requested URL returned error: 407"
2020-10-22 19:32:51,910 P3549 [INFO]    Trying other mirror.
2020-10-22 19:32:51,911 P3549 [INFO]    195 packages excluded due to repository priority protections
2020-10-22 19:32:51,911 P3549 [INFO]    Resolving Dependencies
2020-10-22 19:32:51,911 P3549 [INFO]    --> Running transaction check
2020-10-22 19:32:51,911 P3549 [INFO]    ---> Package awscli.noarch 0:1.18.107-1.amzn2.0.1 will be updated
2020-10-22 19:32:51,911 P3549 [INFO]    ---> Package awscli.noarch 0:1.18.147-1.amzn2.0.1 will be an update
2020-10-22 19:32:51,911 P3549 [INFO]    ---> Package ec2-net-utils.noarch 0:1.4-2.amzn2 will be updated
2020-10-22 19:32:51,911 P3549 [INFO]    ---> Package ec2-net-utils.noarch 0:1.4-3.amzn2 will be an update
2020-10-22 19:32:51,911 P3549 [INFO]    ---> Package kernel.x86_64 0:4.14.198-152.320.amzn2 will be installed


2020-10-22 19:32:51,914 P3549 [INFO]    Transaction Summary
2020-10-22 19:32:51,914 P3549 [INFO]    ================================================================================
2020-10-22 19:32:51,914 P3549 [INFO]    Install   3 Packages
2020-10-22 19:32:51,914 P3549 [INFO]    Upgrade  12 Packages
2020-10-22 19:32:51,914 P3549 [INFO]
2020-10-22 19:32:51,915 P3549 [INFO]    Total download size: 30 M
2020-10-22 19:32:51,915 P3549 [INFO]    Downloading packages:
2020-10-22 19:32:51,915 P3549 [INFO]    Delta RPMs disabled because /usr/bin/applydeltarpm not installed.
2020-10-22 19:32:51,915 P3549 [INFO]    warning: /var/cache/yum/x86_64/2/epel/packages/python2-lockfile-0.11.0-17.el7.noarch.rpm: Header V3 RSA/SHA256 Signature, key ID 352c64e5: NOKEY
2020-10-22 19:32:51,915 P3549 [INFO]    Public key for python2-lockfile-0.11.0-17.el7.noarch.rpm is not installed
2020-10-22 19:32:51,915 P3549 [INFO]    --------------------------------------------------------------------------------
2020-10-22 19:32:51,915 P3549 [INFO]    Total                                              9.9 MB/s |  30 MB  00:03
2020-10-22 19:32:51,915 P3549 [INFO]    Retrieving key from file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7
2020-10-22 19:32:51,915 P3549 [INFO]    Importing GPG key 0x352C64E5:
2020-10-22 19:32:51,915 P3549 [INFO]     Userid     : "Fedora EPEL (7) <epel@fedoraproject.org>"
2020-10-22 19:32:51,915 P3549 [INFO]     Fingerprint: 91e9 7d7c 4a5e 96f1 7f3e 888f 6a2f aea2 352c 64e5
2020-10-22 19:32:51,915 P3549 [INFO]     Package    : epel-release-7-11.noarch (@amzn2extra-epel)
2020-10-22 19:32:51,915 P3549 [INFO]     From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7
2020-10-22 19:32:51,915 P3549 [INFO]    Running transaction check
2020-10-22 19:32:51,915 P3549 [INFO]    Running transaction test
2020-10-22 19:32:51,915 P3549 [INFO]    Transaction test succeeded
2020-10-22 19:32:51,916 P3549 [INFO]    Running transaction
2020-10-22 19:32:51,916 P3549 [INFO]      Updating   : rpm-4.11.3-40.amzn2.0.5.x86_64                              1/29
2020-10-22 19:32:51,916 P3549 [INFO]      Updating   : rpm-libs-4.11.3-40.amzn2.0.5.x86_64                         2/29


2020-10-22 19:33:12,842 P3549 [INFO] ============================================================
2020-10-22 19:33:12,842 P3549 [INFO] Command f_update_clamav_db
2020-10-22 19:34:06,562 P3549 [INFO] -----------------------Command Output-----------------------
2020-10-22 19:34:06,562 P3549 [INFO]    Connecting via bcpxy.nycnet
2020-10-22 19:34:06,562 P3549 [INFO]    ClamAV update process started at Thu Oct 22 19:33:12 2020
2020-10-22 19:34:06,563 P3549 [INFO]    daily database available for download (remote version: 25965)
2020-10-22 19:34:06,563 P3549 [INFO]    Testing database: '/var/lib/clamav/tmp.4f30e/clamav-5b64e065eba885d51401e7bd049f4583.tmp-daily.cvd' ...
2020-10-22 19:34:06,563 P3549 [INFO]    Database test passed.
2020-10-22 19:34:06,563 P3549 [INFO]    daily.cvd updated (version: 25965, sigs: 4334114, f-level: 63, builder: raynman)
2020-10-22 19:34:06,563 P3549 [INFO]    main database available for download (remote version: 59)
2020-10-22 19:34:06,563 P3549 [INFO]    Testing database: '/var/lib/clamav/tmp.4f30e/clamav-cf2a8461309811d4db9d5341b94d8f2d.tmp-main.cvd' ...
2020-10-22 19:34:06,563 P3549 [INFO]    Database test passed.
2020-10-22 19:34:06,563 P3549 [INFO]    main.cvd updated (version: 59, sigs: 4564902, f-level: 60, builder: sigmgr)
2020-10-22 19:34:06,563 P3549 [INFO]    bytecode database available for download (remote version: 331)
2020-10-22 19:34:06,563 P3549 [INFO]    Testing database: '/var/lib/clamav/tmp.4f30e/clamav-8f4d96e658e191a44867e16d5d578c73.tmp-bytecode.cvd' ...
2020-10-22 19:34:06,563 P3549 [INFO]    Database test passed.
2020-10-22 19:34:06,563 P3549 [INFO]    bytecode.cvd updated (version: 331, sigs: 94, f-level: 63, builder: anvilleg)
2020-10-22 19:34:06,563 P3549 [INFO] ------------------------------------------------------------
2020-10-22 19:34:06,563 P3549 [INFO] Completed successfully.
2020-10-22 19:34:06,564 P3549 [INFO] ============================================================
2020-10-22 19:34:06,564 P3549 [INFO] Command g_a_curlrc
2020-10-22 19:34:06,567 P3549 [INFO] Completed successfully.
2020-10-22 19:34:06,568 P3549 [INFO] ============================================================



2020-10-22 19:34:06,585 P3549 [INFO] Command g_systemctl_enable_clamd
2020-10-22 19:34:06,652 P3549 [INFO] -----------------------Command Output-----------------------
2020-10-22 19:34:06,653 P3549 [INFO]    Created symlink from /etc/systemd/system/multi-user.target.wants/clamd@scan.service to /usr/lib/systemd/system/clamd@.service.
2020-10-22 19:34:06,653 P3549 [INFO] ------------------------------------------------------------
2020-10-22 19:34:06,653 P3549 [INFO] Completed successfully.
2020-10-22 19:34:06,653 P3549 [INFO] ============================================================
2020-10-22 19:34:06,653 P3549 [INFO] Test for Command h_systemctl_start_clamd
2020-10-22 19:34:06,659 P3549 [INFO] -----------------------Command Output-----------------------
2020-10-22 19:34:06,659 P3549 [INFO]    inactive
2020-10-22 19:34:06,659 P3549 [INFO] ------------------------------------------------------------
2020-10-22 19:34:06,659 P3549 [INFO] Completed successfully.
2020-10-22 19:34:06,660 P3549 [INFO] ============================================================
2020-10-22 19:34:06,660 P3549 [INFO] Command h_systemctl_start_clamd
2020-10-22 19:34:29,083 P3549 [INFO] Completed successfully.


========================= cfn-init.log =========================

2020-10-22 19:31:27,124 [DEBUG] Running command a_installs
2020-10-22 19:31:27,125 [DEBUG] No test for command a_installs
2020-10-22 19:32:51,931 [INFO] Command a_installs succeeded
2020-10-22 19:32:51,931 [DEBUG] Command a_installs output: Loaded plugins: extras_suggestions, langpacks, priorities, update-motd
https://ewr.edge.kernel.org/fedora-buffet/epel/7/x86_64/repodata/256fe13c9b4274f5ab2b2c61d51d961ff7d1bb89cd8d57b6dffe1c9e78570aae-primary.sqlite.bz2: [Errno 14] curl#22 - "The requested URL returned error: 407"
Trying other mirror.
https://mirror.atl.genesisadaptive.com/epel/7/x86_64/repodata/7c541c1a27282c7f6dfe8a30f176650d03d56eb9a014cf00b2b9775c958aa6e3-updateinfo.xml.bz2: [Errno 14] curl#22 - "The requested URL returned error: 407"
Trying other mirror.
http://mirror.twinlakes.net/epel/7/x86_64/repodata/7c541c1a27282c7f6dfe8a30f176650d03d56eb9a014cf00b2b9775c958aa6e3-updateinfo.xml.bz2: [Errno 14] HTTP Error 407 - Proxy Authentication Required
Trying other mirror.
https://mirror.arizona.edu/fedora-epel/7/x86_64/repodata/256fe13c9b4274f5ab2b2c61d51d961ff7d1bb89cd8d57b6dffe1c9e78570aae-primary.sqlite.bz2: [Errno 14] curl#22 - "The requested URL returned error: 407"
Trying other mirror.
https://epel.mirror.constant.com/7/x86_64/repodata/256fe13c9b4274f5ab2b2c61d51d961ff7d1bb89cd8d57b6dffe1c9e78570aae-primary.sqlite.bz2: [Errno 14] curl#22 - "The requested URL returned error: 407"
Trying other mirror.
195 packages excluded due to repository priority protections
Resolving Dependencies
--> Running transaction check
---> Package awscli.noarch 0:1.18.107-1.amzn2.0.1 will be updated
---> Package awscli.noarch 0:1.18.147-1.amzn2.0.1 will be an update
---> Package ec2-net-utils.noarch 0:1.4-2.amzn2 will be updated


========================= cloud-init.log =========================

Oct 22 19:30:56 cloud-init[3530]: util.py[DEBUG]: Running command ['/var/lib/cloud/instance/scripts/part-001'] with allowed return codes [0] (shell=True, capture=False)
Oct 22 19:39:30 cloud-init[3530]: util.py[WARNING]: Failed running /var/lib/cloud/instance/scripts/part-001 [1]
Oct 22 19:39:30 cloud-init[3530]: util.py[DEBUG]: Failed running /var/lib/cloud/instance/scripts/part-001 [1]
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cloudinit/util.py", line 910, in runparts
    subp(prefix + [exe_path], capture=False, shell=True)
  File "/usr/lib/python2.7/site-packages/cloudinit/util.py", line 2105, in subp
    cmd=args)
ProcessExecutionError: Unexpected error while running command.
Command: ['/var/lib/cloud/instance/scripts/part-001']
Exit code: 1
Reason: -
Stdout: -
Stderr: -
Oct 22 19:39:30 cloud-init[3530]: cc_scripts_user.py[WARNING]: Failed to run module scripts-user (scripts in /var/lib/cloud/instance/scripts)
Oct 22 19:39:30 cloud-init[3530]: handlers.py[DEBUG]: finish: modules-final/config-scripts-user: FAIL: running config-scripts-user with frequency once-per-instance
Oct 22 19:39:30 cloud-init[3530]: util.py[WARNING]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_scripts_user.pyc'>) failed
Oct 22 19:39:30 cloud-init[3530]: util.py[DEBUG]: Running module scripts-user (<module 'cloudinit.config.cc_scripts_user' from '/usr/lib/python2.7/site-packages/cloudinit/config/cc_scripts_user.pyc'>) failed
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/cloudinit/stages.py", line 851, in _run_modules
    freq=freq)
  File "/usr/lib/python2.7/site-packages/cloudinit/cloud.py", line 54, in run
    return self._runners.run(name, functor, args, freq, clear_on_fail)
  File "/usr/lib/python2.7/site-packages/cloudinit/helpers.py", line 187, in run

Oct 22 19:39:31 cloud-init[3530]: main.py[DEBUG]: Ran 9 modules with 1 failures
Oct 22 19:39:31 cloud-init[3530]: atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/status.json (via temporary file /var/lib/cloud/data/tmpGnzntz) - w: [644] 668 bytes/chars
Oct 22 19:39:31 cloud-init[3530]: atomic_helper.py[DEBUG]: Atomically writing to file /var/lib/cloud/data/result.json (via temporary file /var/lib/cloud/data/tmpKmjMsu) - w: [644] 153 bytes/chars
Oct 22 19:39:31 cloud-init[3530]: util.py[DEBUG]: Creating symbolic link from '/run/cloud-init/result.json' => '../../var/lib/cloud/data/result.json'
Oct 22 19:39:31 cloud-init[3530]: util.py[DEBUG]: Reading from /proc/uptime (quiet=False)
Oct 22 19:39:31 cloud-init[3530]: util.py[DEBUG]: Read 14 bytes from /proc/uptime
Oct 22 19:39:31 cloud-init[3530]: util.py[DEBUG]: cloud-init mode 'modules' took 515.013 seconds (515.01)
Oct 22 19:39:31 cloud-init[3530]: handlers.py[DEBUG]: finish: modules-final: FAIL: running modules for final

**Comment by rmarre** [comment]
All proxy issues are fixed and able to start scan files, however logs shows below error with clamdscan exit status was 2. 

Oct 23 04:24:51 ip-.... s3-virusscan[10898]: message failed: #<RuntimeError: s3://clamav-scanfiles01/TestFile500KB.txt  could not be scanned, clamdscan exit status was 2, retry> 
#<struct Aws::SQS::Types::Message message_id="f3980ab3-1ce8-4cee-b790-67c2d92ef58c", 
receipt_handle="AQEBnx5PwoPFKdnnn1yfYmgmWN+5....85EXN+14=", 
md5_of_body="791663dbc882cbce7eafd181f2651387", 
body="{\"Records\":[{\"eventVersion\":\"2.1\",\"eventSource\":\"aws:s3\",\"awsRegion\":
\"us-east-1\",\"eventTime\":\"2020-10-23T04:24:44.083Z\",\"eventName\":
\"ObjectCreated:Put\",\"userIdentity\":{\"principalId\":\"AWS:AROAYTYKAGB....:rmarre@......\"},
\"requestParameters\":{\"sourceIPAddress\":\"98.156.7.83\"},\"responseElements\":{\"x-amz-request-id\":
\"CQ2GEN2J1NAW6K8J\",\"x-amz-id-2\":\"8ux7BN5.........13OOP4GD4CG9JpvS3b+0tD4E5mrbQ\"},
\"s3\":{\"s3SchemaVersion\":\"1.0\",\"configurationId\":\"s3-virusscan\",\"bucket\":{\"name\":
\"clamav-scanfiles01\",\"ownerIdentity\":{\"principalId\":\"AHOH5ARU52ARV\"},
\"arn\":\"arn:aws:s3:::clamav-scanfiles01\"},\"object\":{\"key\":\"TestFile500KB.txt\",
\"size\":448,\"eTag\":\"a50abfa4c1936b1ad71c0331f3808562\",\"sequencer\":\"005F925B11EFC8813E\"}}}]}",
 attributes={"SenderId"=>"AIDAJHIPRHEMV73VRJEBU", "ApproximateFirstReceiveTimestamp"=>"1603427091076", 
 "ApproximateReceiveCount"=>"1", "SentTimestamp"=>"1603427091070"}, 
 md5_of_message_attributes=nil, message_attributes={}>
Oct 23 04:24:51 ip-.... s3-virusscan[10898]: worker failed: 
#<RuntimeError: s3://dotapadev-clamav-scanfiles01/TestFile500KB.txt  could not be scanned, clamdscan exit status was 2, retry>

Appreciate your help, thanks.

**Comment by andreaswittig** [comment]
Can't tell from the logs. My assumption is, that ClamAV is not working correctly due to a proxy issue. Please check the logs from `/var/log/cron`.

**Comment by rmarre** [comment]
Issue has been resolved by adding below details in trust relationships for configured IAM role. 
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Service": "ec2.amazonaws.com"
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
